version: "3.3"
services:
  iframe1:
    image: node:lts
    ports:
      - "8081:8080"
    container_name: iframe-1
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn --frozen-lockfile && yarn serve"

  iframe2:
    image: node:lts
    ports:
      - "8082:8080"
    container_name: iframe-2
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn --frozen-lockfile && yarn serve"

  parent:
    image: node:lts
    ports:
      - "8080:5000"
    container_name: iframe-parent
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npx serve public/parent"
